version: "2"
services:
  dancer:
    image: vampouille/docker-party-dancer:latest
    build: dancer/
    entrypoint: /bin/bash
    tty: true
  house:
    image: vampouille/docker-party-house:latest
    build: house/
    ports:
      - "2234:22"
    environment:
      HOUSE_USER: root
      HOUSE_HOST: 172.17.0.1
      HOUSE_PORT: 2234
