export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="dockerparty"
zstyle ':omz:update' mode disabled
COMPLETION_WAITING_DOTS="true"
plugins=(docker)
source $ZSH/oh-my-zsh.sh
export LANG=fr_FR.UTF-8
export LC_ALL=fr_FR.UTF-8
